FROM python:3.10-slim

WORKDIR /app

# System dependency for LightGBM
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --default-timeout=100 -r requirements.txt

COPY src ./src
COPY artifacts ./artifacts

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.training.train"]